### ISSUE TITLE
请教关于该库的实现原理和使用场景的理解

### ISSUE THREAD

**Issue by zhenlanghuo** [crazybie/linear_ac#3]
你好，我是从 [如何缓解Golang大型游戏服务器的GC压力](https://zhuanlan.zhihu.com/p/404334020) 这篇文章了解到这个库的
我看完你的文章，我的理解如下
1. 实现原理：使用lac分配的对象，都是[]byte数组划分出来的对象，gc不会递归地扫描对象包含的指针（对象指针指向的内存块是[]byte数组，而对象可能包含多个指针字段），所以能够减少gc时扫描的对象，从而减少gc扫描时间
2. 使用场景：使用lac分配的对象，使用切片或者map进行存储，方便查询

然后我自己写了下面的测试代码来测试gc时间

```
package main

import (
	"fmt"
	"github.com/crazybie/linear_ac/lac"
	"runtime"
	"time"
)

var ac *lac.Allocator

type PbItem struct {
	Id     *int
	Price  *int
	Class  *int
	Name   *string
	Active *bool
}

type PbData struct {
	Age   *int
	Items []*PbItem
	InUse *PbItem
}

func main() {
	acPool := lac.NewAllocatorPool("test", nil, 10000, 64*1024, 32*1000, 64*1000)
	ac := acPool.Get()
	defer ac.Release()

	m := testWithLac()
	for i := 0; i < 10; i++ {
		start := time.Now()
		runtime.GC()
		fmt.Printf("GC took %s\n", time.Since(start))
	}
	runtime.KeepAlive(m)
}

func testWithLac() map[int]*PbData {
	m := make(map[int]*PbData, 1e7)
	for k := 0; k < 1e7; k++ {
		d := lac.New[PbData](ac)
		d.Age = ac.Int(11)

		n := 3
		for i := 0; i < n; i++ {
			item := lac.New[PbItem](ac)
			item.Id = ac.Int(i + 1)
			item.Active = ac.Bool(true)
			item.Price = ac.Int(100 + i)
			item.Class = ac.Int(3 + i)
			item.Name = ac.String("name")

			d.Items = lac.Append(ac, d.Items, item)
		}
		m[k] = d
	}

	return m
}

func testWithRaw() map[int]*PbData {
	m := make(map[int]*PbData, 1e7)
	for k := 0; k < 1e7; k++ {
		age := 1

		d := &PbData{
			Age: &age,
		}

		n := 3
		for i := 0; i < n; i++ {
			id := i + 1
			active := true
			price := 100 + i
			class := 3 + i
			name := "name"

			item := &PbItem{
				Id:     &id,
				Active: &active,
				Price:  &price,
				Class:  &class,
				Name:   &name,
			}

			d.Items = append(d.Items, item)
		}
                m[k] = d
	}

	return m
}
```

但是测试出来的结果是使用lac分配对象，gc的时间并没有明显更短，是我的实现原理理解不对还是使用场景理解不对？

**Comment by zhenlanghuo** [comment]
文章里的这段话应该是要怎么理解呢 
> 为什么byte数组化分出来的对象也是被指针引用，GC就不扫描呢，因为GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的，细节请看go的垃圾回收文档。虽然有指针引用我们分配的对象，但是从这个指针指向的地址去找heap中对应的内存块的时候，找到的是byte数组，他的对象信息里面是没有子对象的，因此此处的扫描结束。

byte数组划分出来的对象也是被指针引用，这个指针指的是什么形式
`
d := lac.New[PbData](ac)
`
是像变量d这种形式吗，d是一个*PbData类型的变量，你上面说的意思是，gc从这个指针指向的地址去找堆中对应的内存块时，找到的byte数组，他的对象信息里没有子对象，因此该变量d的扫描就结束了，但是我用reflectValue去获取这个变量d的对象信息，是能够获取到这个对象里子对象的（比如 Items 字段），所以需要请教这里指的子对象是什么意思

**Comment by limpo1989** [comment]
@zhenlanghuo 你的代码有一处赋值不对，修改 `:=` 为 `=`

```go
func main() {
	acPool := lac.NewAllocatorPool("test", nil, 10000, 64*1024, 32*1000, 64*1000)
	ac := acPool.Get()  // 修改 `:=` 为 `=`
```

**Comment by zhenlanghuo** [comment]
> 

把这个改正之后，确实能看见效果，用lac分配对象，gc时间确实是减少了

**Comment by zhenlanghuo** [comment]
> @zhenlanghuo 你的代码有一处赋值不对，修改 `:=` 为 `=`
> 
> ```go
> func main() {
> 	acPool := lac.NewAllocatorPool("test", nil, 10000, 64*1024, 32*1000, 64*1000)
> 	ac := acPool.Get()  // 修改 `:=` 为 `=`
> ```

把这个改正之后，确实能看见效果，用lac分配对象，gc时间确实是减少了

**Comment by zhenlanghuo** [comment]
> @zhenlanghuo 你的代码有一处赋值不对，修改 `:=` 为 `=`
> 
> ```go
> func main() {
> 	acPool := lac.NewAllocatorPool("test", nil, 10000, 64*1024, 32*1000, 64*1000)
> 	ac := acPool.Get()  // 修改 `:=` 为 `=`
> ```

@limpo1989 把这个改正之后，确实能看见效果，用lac分配对象，gc时间确实是减少了

**Comment by zhenlanghuo** [comment]
> 文章里的这段话应该是要怎么理解呢
> 
> > 为什么byte数组化分出来的对象也是被指针引用，GC就不扫描呢，因为GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的，细节请看go的垃圾回收文档。虽然有指针引用我们分配的对象，但是从这个指针指向的地址去找heap中对应的内存块的时候，找到的是byte数组，他的对象信息里面是没有子对象的，因此此处的扫描结束。
> 
> byte数组划分出来的对象也是被指针引用，这个指针指的是什么形式 `d := lac.New[PbData](ac)` 是像变量d这种形式吗，d是一个*PbData类型的变量，你上面说的意思是，gc从这个指针指向的地址去找堆中对应的内存块时，找到的byte数组，他的对象信息里没有子对象，因此该变量d的扫描就结束了，但是我用reflectValue去获取这个变量d的对象信息，是能够获取到这个对象里子对象的（比如 Items 字段），所以需要请教这里指的子对象是什么意思

@limpo1989 请问你是怎么理解这段话的，你认为用lac分配对象，gc时间减少的原因就是因为上面说的gc扫描到lac分配的对象指针时， 找到指针对应的内存块会发现是byte数组的某一段内存就结束扫描了吗？

**Comment by limpo1989** [comment]
所有lac分配出来的对象都指向lac，也就是lac是他们的父级对象，父级对象lac实际是一个 []byte 不管多大只需要检查一次就行，也就是说只要父级lac还是活着的，那么它分配出来的所有子对象都必定是活着的，因此在扫描子对象时发现指向的是lac，因此这里就可以用lac的状态决定子对象的存活状态，提前结束扫描，我是这样理解的 @zhenlanghuo

**Comment by zhenlanghuo** [comment]
> 所有lac分配出来的对象都指向lac，也就是lac是他们的父级对象，父级对象lac实际是一个 []byte 不管多大只需要检查一次就行，也就是说只要父级lac还是活着的，那么它分配出来的所有子对象都必定是活着的，因此在扫描子对象时发现指向的是lac，因此这里就可以用lac的状态决定子对象的存活状态，提前结束扫描，我是这样理解的 @zhenlanghuo

@limpo1989 
我又看了一下原文章那一段话

> 为什么byte数组化分出来的对象也是被指针引用，GC就不扫描呢，因为GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的，细节请看go的垃圾回收文档。虽然有指针引用我们分配的对象，但是从这个指针指向的地址去找heap中对应的内存块的时候，找到的是byte数组，他的对象信息里面是没有子对象的，因此此处的扫描结束。

“因为GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的，细节请看go的垃圾回收文档”
你知道这里指的go的垃圾回收文档是指哪一篇吗？我想看看原文是怎么描述 “GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的” 这个机制的（底层实现原理）

@crazybie 如果作者大大看见，也麻烦指引一下

**Comment by zhenlanghuo** [comment]
> > 所有lac分配出来的对象都指向lac，也就是lac是他们的父级对象，父级对象lac实际是一个 []byte 不管多大只需要检查一次就行，也就是说只要父级lac还是活着的，那么它分配出来的所有子对象都必定是活着的，因此在扫描子对象时发现指向的是lac，因此这里就可以用lac的状态决定子对象的存活状态，提前结束扫描，我是这样理解的 @zhenlanghuo
> 
> @limpo1989 我又看了一下原文章那一段话
> 
> > 为什么byte数组化分出来的对象也是被指针引用，GC就不扫描呢，因为GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的，细节请看go的垃圾回收文档。虽然有指针引用我们分配的对象，但是从这个指针指向的地址去找heap中对应的内存块的时候，找到的是byte数组，他的对象信息里面是没有子对象的，因此此处的扫描结束。
> 
> “因为GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的，细节请看go的垃圾回收文档” 你知道这里说的go的垃圾回收文档是指哪一篇吗？我想看看原文是怎么描述 “GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的” 这个机制的（底层实现原理）
> 
> @crazybie 如果作者大大看见，也麻烦指引一下

看了一下 [如何缓解Golang大型游戏服务器的GC压力](https://zhuanlan.zhihu.com/p/404334020) 原文的参考文献
作者说的 go的垃圾回收文档应该是指 [GopherCon 2018 - Allocator Wrestling](https://about.sourcegraph.com/blog/go/gophercon-2018-allocator-wrestling) 这一篇，然后结合我找到的另外一篇文章 [深度剖析 Golang 的 GC 扫描对象实现](https://liqingqiya.github.io/golang/gc/%E6%89%AB%E6%8F%8F%E5%AF%B9%E8%B1%A1/2020/07/30/gc-scan-object.html)

“为什么byte数组化分出来的对象也是被指针引用，GC就不扫描呢，因为GO的GC是根据GO分配对象当时的对象信息来确定要不要扫描的，细节请看go的垃圾回收文档。虽然有指针引用我们分配的对象，但是从这个指针指向的地址去找heap中对应的内存块的时候，找到的是byte数组，他的对象信息里面是没有子对象的，因此此处的扫描结束。”
这段话背后的底层原理大致如下
1. 向go申请内存的时候，mallocgc会根据编译期间针对每个 struct 生成的 type 结构，来设置 gc 需要扫描的位图，也就是指针 bitmap；lac内存分配器向内存申请的是[]byte，所以[]byte所在内存块 heapArena 中的bitmap只会记录[]byte数组指针
2. 在gc扫描时，对于堆对象的扫描，scanobject是根据指针地址找到对应的内存块heapArena，然后根据bitmap去找有指针的地方进行扫描
3. lac分配器new出来的对象实际是从[]byte数组里划分一段空间再通过unsafe.Pointer指针强转的，没有针对这个对象向go申请内存（申请的是[]byte数组内存），所以new出来的对象里不管包含了多少个指针，都不会反应在对应的 heapArena 的 bitmap 里，gc扫描的时候也就不会往下扫描

@limpo1989

**Comment by crazybie** [comment]
是这样的。
